name: 'Travel Stipend Calculator'
description: 'Calculate travel stipend for conference and business trips'
inputs:
  location:
    description: 'Destination location (e.g. "Singapore, SG")'
    required: true
  conference_start:
    description: 'Conference start date (e.g. "20 May 2025")'
    required: true
  conference_end:
    description: 'Conference end date'
    required: false
  conference_name:
    description: 'Conference name'
    required: false
  days_before:
    description: 'Days to arrive before conference'
    required: false
    default: '1'
  days_after:
    description: 'Days to leave after conference'
    required: false
    default: '1'
  ticket_price:
    description: 'Conference ticket price'
    required: false
outputs:
  stipend:
    description: 'Travel stipend calculation results'
runs:
  using: 'node20'
  main: 'index.js'