name: Batch Travel Stipend Calculation

on:
  workflow_dispatch:
    inputs:
      origins:
        description: "List of origin cities (comma-separated)"
        required: true
        type: string
      destinations:
        description: "List of destination cities (comma-separated)"
        required: true
        type: string
      start_dates:
        description: "List of conference start dates (comma-separated)"
        required: true
        type: string
      end_dates:
        description: "List of conference end dates (comma-separated), blank = same as start date"
        required: false
        type: string
        default: ""
      ticket_prices:
        description: "List of conference ticket prices (comma-separated), blank = 0"
        required: false
        type: string
        default: ""

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1

      - name: Process Inputs
        id: set-matrix
        run: |
          # Save inputs to files with commas
          echo "${{ inputs.origins }}" | tr ',' '\n' > origins.txt
          echo "${{ inputs.destinations }}" | tr ',' '\n' > destinations.txt
          echo "${{ inputs.start_dates }}" | tr ',' '\n' > start_dates.txt
          echo "${{ inputs.end_dates }}" | tr ',' '\n' > end_dates.txt
          echo "${{ inputs.ticket_prices }}" | tr ',' '\n' > ticket_prices.txt

          # Generate matrix and store in variable (redirect stderr to avoid logging in output)
          matrix=$(bun .github/scripts/generate-stipend-matrix.ts 2>/dev/null)

          # Debug output
          echo "Generated matrix:"
          echo "$matrix"

          # Set the output
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  calculate:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false # Continue other jobs if one fails
    outputs:
      result: ${{ steps.calculate.outputs.result }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Calculate Stipend
        env:
          INPUT_ORIGIN: ${{ matrix.origin }}
          INPUT_DESTINATION: ${{ matrix.destination }}
          INPUT_CONFERENCE_START: ${{ matrix.startDate }}
          INPUT_CONFERENCE_END: ${{ matrix.endDate }}
          INPUT_TICKET_PRICE: ${{ matrix.price }}
          INPUT_OUTPUT_FORMAT: "json"
        id: calculate
        run: |
          # Run once with JSON output and save to file
          bun src/github-action-handler.ts --output-file "results-${{ matrix.destination }}-${{ matrix.startDate }}.json"

          # For logs, run again with table format
          bun src/github-action-handler.ts --output-format table

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.destination }}-${{ matrix.startDate }}
          path: results-${{ matrix.destination }}-${{ matrix.startDate }}.json
          retention-days: 5

  consolidate:
    needs: [calculate]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          path: matrix-results
          pattern: result-*
          merge-multiple: true

      - name: Create Sample Results Directory
        run: |
          mkdir -p sample-results
          cp matrix-results/results-*.json sample-results/ || true

      - name: Consolidate Results
        run: bun .github/scripts/consolidate-stipend-results.ts

      - name: Upload Consolidated Results
        uses: actions/upload-artifact@v4
        with:
          name: travel-stipend-results
          path: |
            consolidated-results.md
            consolidated-results/
          retention-days: 5
