name: Batch Travel Stipend Calculation

on:
  push:
  workflow_dispatch:
    inputs:
      origins:
        description: "List of origin cities (comma-separated)"
        required: true
        type: string
      destinations:
        description: "List of destination cities (comma-separated)"
        required: true
        type: string
      start_dates:
        description: "List of conference start dates (comma-separated)"
        required: true
        type: string
      end_dates:
        description: "List of conference end dates (comma-separated), blank = same as start date"
        required: false
        type: string
        default: ""
      ticket_prices:
        description: "List of conference ticket prices (comma-separated), blank = 0"
        required: false
        type: string
        default: ""

defaults:
  run:
    shell: bash

env:
  TEST_EVENTS: |
    [
      {"name": "Asia Blockchain Summit", "origin": "seoul", "destination": "taipei", "start": "Aug 6", "end": "Aug 8", "price": "0"},
      {"name": "Korea Blockchain Week", "origin": "seoul", "destination": "seoul", "start": "Sep 1", "end": "Sep 7", "price": "0"},
      {"name": "TOKEN2049 Singapore", "origin": "seoul", "destination": "singapore", "start": "Sep 18", "end": "Sep 19", "price": "0"},
      {"name": "GitHub Universe", "origin": "seoul", "destination": "san francisco", "start": "Oct 29", "end": "Oct 30", "price": "0"},
      {"name": "Devcon 7 Bangkok", "origin": "san francisco", "destination": "bangkok", "start": "Nov 12", "end": "Nov 15", "price": "0"},
      {"name": "Consensus Hong Kong", "origin": "seoul", "destination": "hong kong", "start": "Feb 18", "end": "Feb 20", "price": "0"}
    ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Process Inputs
        id: set-matrix
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            # Use test events for push triggers
            echo "Using test events for push trigger"
            # Write properly formatted JSON to file
            echo '${{ env.TEST_EVENTS }}' | jq '.' > test_events.json
            if [ $? -ne 0 ]; then
              echo "Error: Failed to create test events JSON file"
              exit 1
            fi
            matrix=$(bun .github/scripts/generate-stipend-matrix.ts --test-events test_events.json 2>/dev/null)
            if [ $? -ne 0 ]; then
              echo "Error: Failed to generate matrix from test events"
              exit 1
            fi
          else
            # Use workflow inputs for manual triggers
            echo "${{ inputs.origins }}" | tr ',' '\n' > origins.txt
            echo "${{ inputs.destinations }}" | tr ',' '\n' > destinations.txt
            echo "${{ inputs.start_dates }}" | tr ',' '\n' > start_dates.txt
            echo "${{ inputs.end_dates }}" | tr ',' '\n' > end_dates.txt
            echo "${{ inputs.ticket_prices }}" | tr ',' '\n' > ticket_prices.txt
            matrix=$(bun .github/scripts/generate-stipend-matrix.ts 2>/dev/null)
          fi

          # Debug output
          echo "Generated matrix:"
          echo "$matrix"

          # Set the output
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  calculate:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false # Continue other jobs if one fails
    outputs:
      result: ${{ steps.calculate.outputs.result }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Calculate Stipend
        env:
          INPUT_ORIGIN: ${{ matrix.origin }}
          INPUT_DESTINATION: ${{ matrix.destination }}
          INPUT_CONFERENCE_START: ${{ matrix.startDate }}
          INPUT_CONFERENCE_END: ${{ matrix.endDate }}
          INPUT_TICKET_PRICE: ${{ matrix.price }}
          INPUT_OUTPUT_FORMAT: "json"
        id: calculate
        run: |
          # Run once with JSON output and save to file
          bun src/github-action-handler.ts --output-file "results-${{ matrix.destination }}-${{ matrix.startDate }}.json"

          # For logs, run again with table format
          bun src/github-action-handler.ts --output-format table

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.destination }}-${{ matrix.startDate }}
          path: results-${{ matrix.destination }}-${{ matrix.startDate }}.json
          retention-days: 5

  consolidate:
    needs: [calculate]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          path: matrix-results
          pattern: result-*
          merge-multiple: true

      - name: Create Sample Results Directory
        run: |
          mkdir -p sample-results
          cp matrix-results/results-*.json sample-results/ || true

      - name: Consolidate Results
        run: bun .github/scripts/consolidate-stipend-results.ts

      - name: Upload Consolidated Results
        uses: actions/upload-artifact@v4
        with:
          name: travel-stipend-results
          path: |
            consolidated-results.md
            consolidated-results/
          retention-days: 5
