name: Travel Stipend Calculator
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Destination location (e.g. "Singapore, SG")'
        required: true
        type: string
      conference_start:
        description: 'Conference start date (e.g. "20 May 2025")'
        required: true
        type: string
      conference_end:
        description: 'Conference end date'
        required: false
        type: string
      conference_name:
        description: 'Conference name'
        required: false
        type: string
      days_before:
        description: 'Days to arrive before conference'
        required: false
        type: number
        default: 1
      days_after:
        description: 'Days to leave after conference'
        required: false
        type: number
        default: 1
      ticket_price:
        description: 'Conference ticket price'
        required: false
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest
    env:
      DEBUG_GOOGLE_FLIGHTS: true
      CAPTURE_SCREENSHOTS: true
      SCREENSHOT_QUALITY: high
      PUPPETEER_TIMEOUT: 60000
      DETAILED_LOGGING: true
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup debugging environment
        run: |
          mkdir -p debug-screenshots
          mkdir -p debug-logs
          echo "Creating debug directories for artifact collection"
          echo "Current working directory: $(pwd)"
          echo "Chrome version: $(google-chrome --version)"

      - name: Run travel stipend calculator
        id: stipend-calculator
        env:
          INPUT_LOCATION: ${{ github.event.inputs.location }}
          INPUT_CONFERENCE_START: ${{ github.event.inputs.conference_start }}
          INPUT_CONFERENCE_END: ${{ github.event.inputs.conference_end || github.event.inputs.conference_start }}
          INPUT_CONFERENCE_NAME: ${{ github.event.inputs.conference_name }}
          INPUT_DAYS_BEFORE: ${{ github.event.inputs.days_before }}
          INPUT_DAYS_AFTER: ${{ github.event.inputs.days_after }}
          INPUT_TICKET_PRICE: ${{ github.event.inputs.ticket_price }}
          # Pass through GitHub secrets to the script
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Enable more verbose logging for debugging
          export DEBUG=puppeteer:*
          export NODE_DEBUG=puppeteer

          # Run the script with increased timeout
          bun --inspect src/github-action-handler.ts
        timeout-minutes: 10

      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: google-flights-debug-screenshots
          path: debug-screenshots/
          retention-days: 5

      - name: Upload debug logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: google-flights-debug-logs
          path: debug-logs/
          retention-days: 5

      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-screenshots
          path: test-screenshots/
          retention-days: 5
