name: Calculate Travel Stipend

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Conference Location'
        required: true
        type: string
      conference_start:
        description: 'Conference Start Date'
        required: true
        type: string
      conference_end:
        description: 'Conference End Date'
        required: true
        type: string
      conference_name:
        description: 'Conference Name'
        required: true
        type: string
      days_before:
        description: 'Days Before Conference'
        required: false
        default: '1'
        type: string
      days_after:
        description: 'Days After Conference'
        required: false
        default: '1'
        type: string
      ticket_price:
        description: 'Conference Ticket Price'
        required: false
        default: '0'
        type: string
      origin:
        description: 'Origin Location'
        required: false
        default: 'Seoul, Korea'
        type: string

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'  # Initialize and update submodules

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          bun install
          cd src/utils/google-flights-scraper
          bun install
          cd ../../..

      # Run with targeted error logging only
      - name: Calculate stipend
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Running travel stipend calculator with reduced logging"
          echo "Using Chrome path: $(which google-chrome)"

          # Run the GitHub Action handler with proper input environment variables
          bun run src/github-action-handler.ts

          # Display completion message
          echo "✅ Travel stipend calculation completed"
        env:
          # GitHub Action inputs
          INPUT_LOCATION: ${{ inputs.location }}
          INPUT_CONFERENCE_START: ${{ inputs.conference_start }}
          INPUT_CONFERENCE_END: ${{ inputs.conference_end }}
          INPUT_CONFERENCE_NAME: ${{ inputs.conference_name }}
          INPUT_DAYS_BEFORE: ${{ inputs.days_before }}
          INPUT_DAYS_AFTER: ${{ inputs.days_after }}
          INPUT_TICKET_PRICE: ${{ inputs.ticket_price }}
          INPUT_ORIGIN: ${{ inputs.origin }}

          # System configuration
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
          PUPPETEER_TIMEOUT: 60000

          # Logging and debugging
          DEBUG_GOOGLE_FLIGHTS: true
          ENABLE_ERROR_SCREENSHOTS: true
          CAPTURE_SCREENSHOTS: true
          SCREENSHOT_QUALITY: medium
          LOG_LEVEL: info

          # GitHub token for API access if needed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
