name: Travel Stipend Calculator
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Destination location (e.g. "Singapore, SG")'
        required: true
        type: string
      conference_start:
        description: 'Conference start date (e.g. "20 May 2025")'
        required: true
        type: string
      conference_end:
        description: 'Conference end date'
        required: false
        type: string
      conference_name:
        description: 'Conference name'
        required: false
        type: string
      days_before:
        description: 'Days to arrive before conference'
        required: false
        type: number
        default: 1
      days_after:
        description: 'Days to leave after conference'
        required: false
        type: number
        default: 1
      ticket_price:
        description: 'Conference ticket price'
        required: false
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create action handler
        run: |
          mkdir -p .github/actions
          bun run create-stipend-action
