name: Calculate Travel Stipend

on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Destination location (e.g. "Singapore, SG")'
        required: true
        type: string
      conference_start:
        description: 'Conference start date (e.g. "20 May 2025")'
        required: true
        type: string
      conference_end:
        description: 'Conference end date'
        required: true
        type: string
      conference_name:
        description: 'Conference name'
        required: true
        type: string
      days_before:
        description: 'Days to arrive before conference'
        required: false
        default: '1'
        type: string
      days_after:
        description: 'Days to leave after conference'
        required: false
        default: '1'
        type: string
      ticket_price:
        description: 'Conference ticket price'
        required: false
        default: '0'
        type: string
      output_format:
        description: 'Output format (table, json, csv)'
        required: false
        default: 'table'
        type: string

jobs:
  calculate:
    runs-on: ubuntu-latest
    env:
      DEBUG_GOOGLE_FLIGHTS: "true"
      CAPTURE_SCREENSHOTS: "true"
      PUPPETEER_TIMEOUT: "60000"
      DETAILED_LOGGING: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Setup debug directories
        run: |
          mkdir -p test-screenshots
          mkdir -p debug-logs
          mkdir -p html-captures

      - name: Calculate travel stipend
        run: |
          bun run src/github-action-handler.ts
        env:
          INPUT_LOCATION: ${{ github.event.inputs.location }}
          INPUT_CONFERENCE_START: ${{ github.event.inputs.conference_start }}
          INPUT_CONFERENCE_END: ${{ github.event.inputs.conference_end }}
          INPUT_CONFERENCE_NAME: ${{ github.event.inputs.conference_name }}
          INPUT_DAYS_BEFORE: ${{ github.event.inputs.days_before }}
          INPUT_DAYS_AFTER: ${{ github.event.inputs.days_after }}
          INPUT_TICKET_PRICE: ${{ github.event.inputs.ticket_price }}
          INPUT_OUTPUT_FORMAT: ${{ github.event.inputs.output_format }}

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: |
            test-screenshots/
            html-captures/
          retention-days: 5

      - name: Upload debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: debug-logs/
          retention-days: 5

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./**/*-error.png
            ./**/*-error.json
            ./**/*-error.txt
            ./**/*-error.html
          retention-days: 5
