name: Travel Stipend Calculator
on:
  # Run on every push to test with default values
  push:
    branches:
      - '**'  # Run on any branch push

  # Manual dispatch with custom inputs
  workflow_dispatch:
    inputs:
      use_test_defaults:
        description: 'Use default test values (Barcelona, May 20-22, 2025)'
        required: false
        type: boolean
        default: false
      location:
        description: 'Destination location (e.g. "Singapore, SG")'
        required: false  # Not required if using defaults
        type: string
      conference_start:
        description: 'Conference start date (e.g. "20 May 2025")'
        required: false  # Not required if using defaults
        type: string
      conference_end:
        description: 'Conference end date'
        required: false
        type: string
      conference_name:
        description: 'Conference name'
        required: false
        type: string
      days_before:
        description: 'Days to arrive before conference (minimum 1 required)'
        required: false
        type: number
        default: 2
      days_after:
        description: 'Days to leave after conference (minimum 1 required)'
        required: false
        type: number
        default: 1
      ticket_price:
        description: 'Conference ticket price'
        required: false
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest
    env:
      DEBUG_GOOGLE_FLIGHTS: false
      ENABLE_ERROR_SCREENSHOTS: true
      CAPTURE_SCREENSHOTS: false
      SCREENSHOT_QUALITY: medium
      PUPPETEER_TIMEOUT: 60000
      LOG_LEVEL: "error,warning"
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup debugging environment
        run: |
          mkdir -p debug-screenshots
          mkdir -p debug-logs
          mkdir -p test-screenshots
          echo "Creating debug directories for artifact collection"
          echo "Current working directory: $(pwd)"
          echo "Chrome version: $(google-chrome --version)"

      - name: Run travel stipend calculator
        id: stipend-calculator
        env:
          # Use test defaults if specified or if running from push trigger
          INPUT_LOCATION: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && 'Barcelona, Spain' || github.event.inputs.location }}
          INPUT_CONFERENCE_START: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && '20 May 2025' || github.event.inputs.conference_start }}
          INPUT_CONFERENCE_END: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && '22 May 2025' || github.event.inputs.conference_end || github.event.inputs.conference_start }}
          INPUT_CONFERENCE_NAME: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && 'Test Conference 2025' || github.event.inputs.conference_name }}
          INPUT_DAYS_BEFORE: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && '2' || github.event.inputs.days_before }}
          INPUT_DAYS_AFTER: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && '1' || github.event.inputs.days_after }}
          INPUT_TICKET_PRICE: ${{ (github.event_name == 'push' || github.event.inputs.use_test_defaults) && '750' || github.event.inputs.ticket_price }}
          # Pass through GitHub secrets to the script
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run with targeted error logging only
          echo "Running travel stipend calculator with reduced logging"

          # Run the script with increased timeout
          bun src/github-action-handler.ts
        timeout-minutes: 10

      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: google-flights-debug-screenshots
          path: debug-screenshots
          if-no-files-found: ignore
          retention-days: 5

      - name: Upload debug logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: google-flights-debug-logs
          path: debug-logs
          if-no-files-found: ignore
          retention-days: 5

      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: test-screenshots
          if-no-files-found: ignore
          retention-days: 5
