name: Travel Stipend Calculator
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Destination location (e.g. "Singapore, SG")'
        required: true
        type: string
      conference_start:
        description: 'Conference start date (e.g. "20 May 2025")'
        required: true
        type: string
      conference_end:
        description: 'Conference end date'
        required: false
        type: string
      conference_name:
        description: 'Conference name'
        required: false
        type: string
      days_before:
        description: 'Days to arrive before conference'
        required: false
        type: number
        default: 1
      days_after:
        description: 'Days to leave after conference'
        required: false
        type: number
        default: 1
      ticket_price:
        description: 'Conference ticket price'
        required: false
        type: number

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run travel stipend calculator
        id: stipend-calculator
        env:
          INPUT_LOCATION: ${{ github.event.inputs.location }}
          INPUT_CONFERENCE_START: ${{ github.event.inputs.conference_start }}
          INPUT_CONFERENCE_END: ${{ github.event.inputs.conference_end || github.event.inputs.conference_start }}
          INPUT_CONFERENCE_NAME: ${{ github.event.inputs.conference_name }}
          INPUT_DAYS_BEFORE: ${{ github.event.inputs.days_before }}
          INPUT_DAYS_AFTER: ${{ github.event.inputs.days_after }}
          INPUT_TICKET_PRICE: ${{ github.event.inputs.ticket_price }}
        run: bun src/github-action-handler.ts
