name: Run Tests

on:
  push:
    paths:
      - '**.ts'
      - '.github/workflows/**'
      - 'package.json'
      - 'bun.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          cd src/utils/google-flights-scraper
          bun install
          cd ../../..

      - name: Run tests
        run: bun test
